### ISSUE TITLE
Bismillah tidak muncul dibeberapa surah

### ISSUE THREAD

**Issue by Unknown1311SS0304** [abinoval/PowQuran#2]
Kepada developer yang terhormat, saya ingin bertanya perihal beberapa surah yang bismillah nya itu tidak muncul, dan bagaimana cara mengatasinya. Dan apakah saya boleh tahu perihal database yang anda gunakan, dikarenakan saya ingin mengubah beberapa makna yang agak tidak sesuai. Sekian dan terimakasih, sukses selalu buat kalian 🙏

**Comment by powxenv** [comment]
Halo @Unknown1311SS0304, terimakasih atas laporannya, untuk bacaan basmalah sendiri memang kami tidak tampilkan karena di website ini karena kami hanya ingin menampilkan isi surah dari ayat 1 sampai akhir, basmalah hanya di Al-Fatihah karena bacaan basmalah tersebut adalah ayat pertama dari Al-Fatihah, semoga dimengerti. Jika ingin berkontribusi untuk menambahkan bacaan basmalah dipersilakan untuk melakukan pull request. Untuk database sendiri kami tidak menggunakannya, karena seluruh data yang ditampilkan di website ini berdasarkan api dari https://github.com/gadingnst/quran-api, jadi jika ingin mengubah beberapa makna dari surah/ayat bisa berkontribusi di repository https://github.com/gadingnst/quran-api. Terimakasih sekali lagi 😄

**Comment by powxenv** [comment]
Jika tidak ada hal yang ingin disampaikan lagi, saya close ya

**Comment by Unknown1311SS0304** [comment]
Bang boleh kasih saran bagaimana cara munculkan bismillah nya bang?😅.
soalnya kami masih pemula dan tugas projeknya langsung ginian. Kelompok
kami dapat jatah buat Al-Qur'an digital

Pada tanggal Jum, 15 Sep 2023 11.23, Abi Noval Fauzi <
***@***.***> menulis:
